"""Runs DECIMER structure recognition on has_structures=1 figures, flagging
low-confidence results for human review instead of trying to predict
upstream (via CLIP vision or captions) whether a given image is a good
DECIMER target.

That upstream approach was tried first for is_3d specifically and abandoned:
CLIP vision is confounded by ordinary drawing conventions (metal complexes
are routinely drawn with rounded, ball-like atoms even in plain 2D
depictions -- visually similar to a genuine 3D render without being one),
and captions don't always exist for a given figure. DECIMER's own per-token
confidence is a more directly-grounded signal, since it's asking the actual
question that matters: did DECIMER succeed on THIS image, not what visual
category the image belongs to.

Confirmed directly before picking a threshold: a set of clean 2D structures
scored 0.92-0.998 mean confidence, while a 3D ball-and-stick metal-complex
render DECIMER completely misread (fabricated a structure with none of the
real functional groups: no N, no Cl, no metal) scored 0.787. A correctly-
recognized but unusually-colored 2D structure also dipped to 0.790 despite
being right -- confidence isn't perfectly correlated with correctness, but
that's an acceptable asymmetry: flagging a correct structure for human
review is a much cheaper mistake than silently accepting a wrong one.

Confidence alone still misses confirmed, deterministic failure modes:
DECIMER's synthetic training data (generated by RanDepict, which maps
superatom-abbreviation labels to expanded SMILES fragments) has no entry
anywhere for the plain "Ts" (tosyl) abbreviation -- checked directly
against RanDepict's own abbreviation tables and RDKit's built-in default
list. It only defines the far less common "p-Tosyl"/"4-Tosyl"/"Tos"
spellings. Since "Ts" is by far the standard abbreviation in real
synthetic-chemistry literature, the model has essentially never seen it
and reliably misreads it as the element thallium ([Tl]) instead -- visible
even on the public DECIMER web app, not just this pipeline. Thallium is
implausible in routine cross-coupling/catalysis SI documents, and this
substitution happens with moderate-to-high confidence (not a low-
confidence guess), so the existing threshold doesn't catch it. Detecting
the literal label text in the source image via OCR and forcing a review
flag catches this deterministically, independent of what DECIMER's
confidence score says. `--psm 6` (assume one uniform text block) is
required for tesseract to find it -- the default page-segmentation mode
is tuned for structured multi-column pages and fails completely on a
single tight structure crop with sparse embedded text, even though the
label is clearly legible.

Upscaling the crop before OCR turned out to matter more than expected --
not just for accuracy on a given machine, but for reproducibility across
machines. Found by running this exact check on a cloud GPU box for a
larger batch: an identical crop that read "ts" at 96% confidence locally
read as garbage ("+,") on a rented box, even after matching the tesseract
major version and confirming byte-identical eng.traineddata files.
Different tesseract builds (there, conda-forge's; here, Ubuntu apt's)
have different implicit resolution sensitivity for small glyphs, and
without upscaling, a check that passes calibration on one machine can
silently fail on another. 4x upscaling fixed the rented box's read
without changing the local result -- cheap enough to always apply rather
than depend on it happening to not matter this time.

KNOWN_MISSING_ABBREVIATIONS is a small, explicitly-verified list (currently
just "Ts") of labels confirmed absent from DECIMER's training vocabulary --
not a guess. See docs/decimer_abbreviation_gaps.md for how to verify and
add more.

DECIMER Segmentation's `expand` option only dilates the detection mask to
pull in nearby disconnected ink -- it does not add any whitespace margin
around the final crop, so segments come out with only a couple pixels
between the structure and the image edge, and DECIMER's OCSR model (trained
on RanDepict images with generous margins) can hallucinate on a bond
sitting right at that boundary. **Tried white-padding every crop before
OCSR to fix this, then reverted it.** It did fix a real case
(`copper_iron_2025/page4_fig0_seg1.png`, a chlorobenzene crop: tight-crop
read `C1=CC=C(C=C1)[Cl]I` at 0.816 confidence, padded read `Cl` correctly
at 0.897) -- but checking the *original* unpadded confidence on that same
crop and on every other "fixed" case in a 40-image sample showed all of
them were already below MEAN_CONFIDENCE_THRESHOLD and therefore already
correctly flagged for review. Padding added zero net coverage; it only
recomputed confidence on a modified image, which in one case (a genuine
R-group scope-table scaffold) pushed a hallucinated
`...C2=CC=CC=C2.[Pt].[Pt]` above the review threshold -- inventing two
platinum atoms with no basis in the image and removing a correctly-flagged
crop from review. Not worth doubling inference cost for a fix the existing
confidence gate already provides.

GENERIC_SUBSTITUENT_TOKENS catches a different, common case: substrate-scope
and summary-scheme figures routinely draw one scaffold with a generic
substituent (R, R1, R2, ..., X, Z) standing in for "varies across the
table," not a real compound. DECIMER has explicit vocabulary for this --
it emits a genuine bracket atom like [R] or [R2] rather than
mis-recognizing it as something else, so this is a plain regex check on
the SMILES output, no OCR needed. Deliberately excludes Y and Ar even
though they show up the same way in scheme legends: both are also real
element symbols (Yttrium, Argon) that legitimately appear in this corpus's
organometallic structures, so flagging them would false-positive on real
compounds. This is reported as its own field
(`has_generic_substituent`), not folded into need_human_review -- these
crops aren't wrong extractions to correct, they're not real compounds at
all (a human/schema layer, not a compound inventory, is the right
consumer of what scaffold+conditions a scheme describes), so downstream
code should be able to route them differently once that schema layer
exists rather than presenting them for the same kind of review as a
misread structure. They still count toward need_human_review for now
since there's nowhere else to route them yet.

RDKit parseability (`Chem.MolFromSmiles(smiles) is not None`) catches a
real, separate failure category: syntactically/valence-broken SMILES --
unrecognized bracket atoms, impossible interhalogens, illegal ring
closures -- the kind of output that isn't a coherent molecule at all, not
just a wrong one. Confirmed at corpus scale before adding this: of 1,687
already-extracted structures, 161 (9.5%) fail to parse, and 103 of those
were previously accepted silently (only 58 were already caught by the
other checks) -- essentially free coverage, since this only re-parses the
SMILES DECIMER already produced, no extra inference.

It is NOT a general correctness check, though -- confirmed directly this
doesn't catch chemically-valid-but-wrong hallucinations, since RDKit has
no way to know a result doesn't match the source image: the
`...C2=CC=CC=C2.[Pt].[Pt]` hallucination from the padding experiment above
parses fine (bare disconnected atoms are legal), as does an implausible
280-carbon degenerate chain. Both are individually valid molecules by
valence rules alone. So this check is a floor (rejects outputs that
aren't even coherent chemistry), not a ceiling (doesn't validate that a
valid-looking structure is the *right* one).

The Ts-detection OCR check above has two real gaps, both found by tracing
a confirmed silent wrong-answer (a Ts-containing structure DECIMER read as
`C1CN(CCC1C(F)(F)F)[Si]`, reproduced independently on the public web app,
at 0.934 confidence -- well above the review threshold, and undetected by
this check). First: it only ran one OCR pass on the whole image. That's
fine for a tight single-structure crop (what it was originally validated
against), but the zero-segment fallback path (batch_decimer_extract.py
runs OCSR on the original uncropped figure when DECIMER Segmentation
finds nothing) can hand this a much larger, busier image where the label
is too small relative to the whole frame for one pass to read at all --
confirmed directly: a 541x401 fallback image's whole-image OCR found
nothing resembling "Ts", but tiling it 3x3 (same tiling pattern as
figure_classify.py's LOCAL_TAGS, for the same reason -- recovering
detail a whole-frame pass downsamples away) read "TsN" at 90% confidence
in one tile. Second, and more fundamental: the match required an *exact*
token equal to "ts", but the label routinely fuses with the adjacent atom
in the source drawing with no separating space (TsN, OTs, NTs, ...), so
tesseract naturally tokenizes it as one merged word -- "tsn." never equals
"ts", so even a perfect OCR read on that word would have been silently
discarded. Switched to substring matching, which would have caught this
same case even without the tiling fix.

_strip_annotation_text addresses a different, bigger problem than any of
the above: DECIMER's OCSR isn't robust to *anything* sharing the frame
besides the structure itself. Found by manually testing a real, confirmed
example -- a correct core structure with a hallucinated garbage fragment
appended after a "." -- against the public DECIMER web app: clipping out
only the nearby "70% (X = Br)" reaction-condition-variant annotation text
(nothing else changed) took it from a nonsense read
(`...NC2=NC=CS2.Cl[X1].[Cl-].[Cl-]...`, conf 0.876, RDKit-invalid) to the
correct structure alone at conf 0.994. The scope-table margin-expansion
fix above makes this worse, not better, by design -- it was built to
recover truncated substituent labels, but the same generous margin also
reliably pulls in this kind of nearby annotation text. So both problems
share one fix: separate "real chemistry label" text (element symbols,
substituent abbreviations -- keep) from "incidental annotation" text
(yield percentages, "(X = Cl)"-style condition variants, compound-ID
numbers, descriptive words like "Anticancer" -- paint over) before
DECIMER ever sees the crop, rather than trying to make OCSR itself robust
to it.

JUNK_ANNOTATION_TOKEN_RE encodes that split as a content pattern, not a
position, since a rule like "text outside the original tight detection
box" would also strip real recovered labels (the whole point of the
margin fix). Checked against real OCR output from the two confirmed cases
above before trusting it: yield percentages contain "%"; condition
variants tokenize with stray "(", ")", "=" characters DECIMER's own
OCSR vocabulary never produces mid-structure; descriptive words are long
pure-alphabetic runs no real substituent abbreviation matches (COOCH3,
OCH3, NHBoc all mix in digits or fail the length+pure-alpha test);
compound-ID numbers are 1-3 digits with an optional *lowercase* letter
suffix (this corpus's own numbering convention: 3a, 4b, 5d) --
deliberately excludes an uppercase suffix so a real isotope label like
13C or 13CH3 is never touched. Applied unconditionally to every crop
(not just ones already suspected of having extra content) since the
regex is conservative by construction -- verified directly against every
real chemistry token seen so far in this corpus (OMe, Cl, H2N, NH2, Br,
Ts, R2, X1, 13CH3, COOCH3, OCH3) and none of them match.

The bare-digit compound-ID pattern gets a separate, higher confidence bar
(JUNK_NUMBER_MIN_CONFIDENCE) than everything else, found necessary by a
real collateral-damage case: a spurious OCR token "4" (conf 62), actually
a misread fragment of the structure's own "S" ring atom glyph, physically
overlapped a real "CH3" label's bounding box and masking it corrupted the
adjacent real label into an unreadable split "C   H3". Every genuine
compound-ID number seen so far reads at 90+ confidence (29, 52, 5b all
96); this spurious one didn't clear that bar. The other junk patterns
(%, parens, =, long words) don't carry this risk the same way -- they
don't collide with single-glyph misreads of bond/atom line-art the way a
bare 1-2 digit token can.
"""

import tempfile
from pathlib import Path

from DECIMER import predict_SMILES
from PIL import Image, ImageDraw
from rdkit import Chem
from rdkit import RDLogger
import pytesseract
import re

RDLogger.DisableLog("rdApp.*")  # RDKit logs a warning to stderr per parse failure otherwise

MEAN_CONFIDENCE_THRESHOLD = 0.85
OCR_MIN_CONFIDENCE = 50
OCR_UPSCALE = 4
OCR_TILE_THRESHOLD_PX = 400  # see _detected_missing_abbreviations docstring
OCR_TILE_GRID = (3, 3)
# A single tesseract page-segmentation mode is not reliable enough on its
# own for this check -- confirmed on suzuki_nickel_2026/SI page6_fig1_seg15,
# where the sole mode in use (6, "assume a single uniform block of text")
# dropped the trailing "s" off "NHTs" (read "NHT", 92% confidence) and so
# silently missed a real Ts label, while every other mode tested read it
# correctly. But no single mode is a strict upgrade either: a corpus-wide
# spot check (20 already-correctly-flagged cases) found mode 11 alone
# missing 7 of them that mode 6 alone still catches. Trying several modes
# and taking the union of hits (first match wins, short-circuits) recovers
# both -- confirmed 0 misses across that same 20-case sample plus the new
# case, using only modes already validated on real cases here.
OCR_ABBREVIATION_PSM_MODES = (6, 11, 3, 4)
KNOWN_MISSING_ABBREVIATIONS = {"ts"}
GENERIC_SUBSTITUENT_PATTERN = re.compile(r"\[(?:R\d*|X|Z)\]")
JUNK_ANNOTATION_TOKEN_RE = re.compile(r"%|=|[()]|^[A-Za-z]{6,}$")
# Compound-ID numbers (3a, 4b, 52, ...) get their own pattern, checked
# separately at a higher confidence bar -- see _strip_annotation_text
# docstring for why a bare digit match needs more evidence than the other
# junk patterns before it's trusted enough to paint over.
JUNK_NUMBER_TOKEN_RE = re.compile(r"^\d{1,3}[a-z]?$")
JUNK_NUMBER_MIN_CONFIDENCE = 85
JUNK_MASK_PADDING_PX = 2
OCR_PAD_PX = 20
# See _has_too_many_fragments docstring for how this was picked -- corpus-
# scale sizing at the time: >=10 added 25 new flags, >=8 added 47, >=6
# added 103, on top of the 659 already flagged by everything else. Kept as
# a secondary backstop (see MIN_HEAVY_ATOMS_FOR_LARGE_FRAGMENT below for the
# primary signal) and as the sole signal when the SMILES doesn't parse at
# all, since raw "." count is all that's available then.
MAX_DISCONNECTED_FRAGMENTS = 8
# Primary signal, added after a real audit found MAX_DISCONNECTED_FRAGMENTS
# alone missing 5 of 6 confirmed real merge cases on
# copper_iron_2025/images/page3_fig1.png (4-5 total fragments each, well
# under the threshold of 8). Raw fragment COUNT is a poor proxy: DECIMER
# very commonly appends 1-2 small spurious fragments (".CC", ".[F-]",
# ".[Ar]") to an otherwise-correct single-compound SMILES, which inflates
# the count without being a real merge -- corpus-wide, 930+ legitimate
# single-compound entries sit at 1-2 fragments and a long tail of these
# small-junk cases sits at 3-7, exactly where the real merges also live, so
# raising the raw threshold to catch the real merges would flood in far
# more of these than real cases. What actually distinguishes a real merge
# is fragment SIZE, not count: each of the 6 missed cases has 2-3
# fragments with >=5 heavy atoms (full aromatic/sulfonamide substructures,
# each individually plausible as its own compound), while the small-junk
# cases have exactly one large fragment plus 1-2 tiny ones (a counterion,
# a placeholder, a spurious 2-3-atom chain). Corpus-wide check before
# adopting: >=2 large fragments flags 39 previously-unflagged entries, of
# which 19 were already caught by another signal (rdkit_valid=False or low
# confidence) and the other 20 were manually spot-checked -- all genuine
# review-worthy cases (the 6 confirmed merges, plus other real OCSR
# failures this metric incidentally also catches, like a hallucinated
# 70+-carbon spurious alkyl chain glued onto an otherwise normal
# structure). No false positives found in the sample checked.
MIN_HEAVY_ATOMS_FOR_LARGE_FRAGMENT = 5
MAX_LARGE_FRAGMENTS = 2


def _has_generic_substituent(smiles):
    return bool(GENERIC_SUBSTITUENT_PATTERN.search(smiles))


def _has_too_many_fragments(smiles, mol):
    """Flags a SMILES with more disconnected fragments than a real single
    compound (plus maybe one real counterion) would plausibly have -- a
    cheap, deterministic backstop for a failure mode confirmed by two real
    cases DECIMER Segmentation can't currently avoid: several compounds
    packed too tightly for it to detect as separate structures (a dense
    scope-table row -- copper_iron_2025/page3_fig1_seg13.png and _seg20.png,
    each 3 real compounds merged into one segment, neither a whitespace nor
    a vector-geometry gap exists between them at the source PDF level to
    re-split on), and a milder, more common pattern of DECIMER appending
    1-2 spurious bare-element fragments ([B], [V], [K], ...) to an
    otherwise-correctly-read single compound on the same scope-table page.
    Both produce a SMILES RDKit accepts as syntactically valid (disconnected
    bare atoms are legal by valence rules alone -- see rdkit_valid's
    docstring above for the same caveat), so neither is caught by the
    existing checks; both cases the pipeline actually hit scored 0.90-0.91
    confidence, comfortably above MEAN_CONFIDENCE_THRESHOLD too.

    Two signals, either one sufficient: (1) MAX_LARGE_FRAGMENTS or more
    fragments with >=MIN_HEAVY_ATOMS_FOR_LARGE_FRAGMENT heavy atoms each --
    the primary signal, see MIN_HEAVY_ATOMS_FOR_LARGE_FRAGMENT's comment
    for why fragment size beats raw fragment count at telling a real merge
    apart from DECIMER's much more common habit of appending small spurious
    fragments to an otherwise-correct single compound. (2)
    MAX_DISCONNECTED_FRAGMENTS raw fragments regardless of size -- a
    backstop for extreme cases (one real case hit 59 raw fragments) and the
    only signal available when mol is None (already-invalid SMILES,
    falls back to counting "." in the raw string) since fragment size can't
    be measured without a parsed mol.

    This does NOT fix the underlying DECIMER Segmentation under-splitting
    (still one crop, one review item covering N real compounds) -- it only
    ensures the result is never silently accepted as a single correct
    compound."""
    if mol is not None:
        frags = Chem.GetMolFrags(mol, asMols=True, sanitizeFrags=False)
        n_large = sum(1 for f in frags if f.GetNumAtoms() >= MIN_HEAVY_ATOMS_FOR_LARGE_FRAGMENT)
        return n_large >= MAX_LARGE_FRAGMENTS or len(frags) >= MAX_DISCONNECTED_FRAGMENTS
    return smiles.count(".") + 1 >= MAX_DISCONNECTED_FRAGMENTS


def _ocr_abbreviation_matches(img):
    """OCRs one image (already cropped to whatever region is being
    checked) and returns the set of KNOWN_MISSING_ABBREVIATIONS confirmed
    present via substring match -- see module docstring for why exact
    token equality silently misses labels fused with an adjacent atom
    (TsN, OTs, ...), and OCR_ABBREVIATION_PSM_MODES's comment for why a
    single page-segmentation mode isn't reliable enough on its own here."""
    scaled = img.resize((img.width * OCR_UPSCALE, img.height * OCR_UPSCALE), Image.LANCZOS)
    found = set()
    for psm in OCR_ABBREVIATION_PSM_MODES:
        data = pytesseract.image_to_data(scaled, config=f"--psm {psm}", output_type=pytesseract.Output.DICT)
        for w, c in zip(data["text"], data["conf"]):
            token = w.strip().lower()
            if not token or c < OCR_MIN_CONFIDENCE:
                continue
            for abbrev in KNOWN_MISSING_ABBREVIATIONS:
                if abbrev in token:
                    found.add(abbrev)
        if found:
            break  # short-circuit once any mode confirms a real hit
    return found


def _strip_annotation_text(img):
    """Paints over OCR-detected annotation text (see module docstring) so
    DECIMER's OCSR only ever sees the structure itself.

    Pads before OCR -- confirmed directly this matters here for the same
    reason it mattered for DECIMER OCSR and DECIMER Segmentation earlier:
    annotation text sitting right at the crop's edge (no margin, since it's
    often the last thing before the original figure's own boundary) reads
    as unrecognizable noise ("70% (X = Br)" -> "(VA","BT]","ee","ul"...,
    nothing matching a junk pattern) without padding, and mostly-cleanly
    with it. The mask coordinates are computed in the padded image's
    space, so OCR_PAD_PX is subtracted back off before drawing on the
    unpadded image actually returned."""
    padded = Image.new("RGB", (img.width + 2 * OCR_PAD_PX, img.height + 2 * OCR_PAD_PX), (255, 255, 255))
    padded.paste(img, (OCR_PAD_PX, OCR_PAD_PX))
    scaled = padded.resize((padded.width * OCR_UPSCALE, padded.height * OCR_UPSCALE), Image.LANCZOS)
    data = pytesseract.image_to_data(scaled, config="--psm 11", output_type=pytesseract.Output.DICT)

    cleaned = img.copy()
    draw = ImageDraw.Draw(cleaned)
    for i in range(len(data["text"])):
        token = data["text"][i].strip()
        conf = data["conf"][i]
        if not token:
            continue
        is_junk = (conf >= OCR_MIN_CONFIDENCE and JUNK_ANNOTATION_TOKEN_RE.search(token)) or (
            conf >= JUNK_NUMBER_MIN_CONFIDENCE and JUNK_NUMBER_TOKEN_RE.search(token)
        )
        if not is_junk:
            continue
        x = data["left"][i] // OCR_UPSCALE - OCR_PAD_PX
        y = data["top"][i] // OCR_UPSCALE - OCR_PAD_PX
        w = data["width"][i] // OCR_UPSCALE
        h = data["height"][i] // OCR_UPSCALE
        draw.rectangle(
            [x - JUNK_MASK_PADDING_PX, y - JUNK_MASK_PADDING_PX,
             x + w + JUNK_MASK_PADDING_PX, y + h + JUNK_MASK_PADDING_PX],
            fill="white",
        )
    return cleaned


def _detected_missing_abbreviations(image_path):
    img = Image.open(image_path).convert("RGB")
    found = _ocr_abbreviation_matches(img)

    if max(img.size) >= OCR_TILE_THRESHOLD_PX:
        w, h = img.size
        rows, cols = OCR_TILE_GRID
        tile_w, tile_h = w // cols, h // rows
        for r in range(rows):
            for c in range(cols):
                x0, y0 = c * tile_w, r * tile_h
                x1 = w if c == cols - 1 else x0 + tile_w
                y1 = h if r == rows - 1 else y0 + tile_h
                found |= _ocr_abbreviation_matches(img.crop((x0, y0, x1, y1)))

    return sorted(found)


def extract_structure(image_path):
    """Returns {"smiles": str, "mean_confidence": float,
    "need_human_review": bool, "detected_missing_abbreviations": [str],
    "has_generic_substituent": bool, "rdkit_valid": bool,
    "too_many_fragments": bool}."""
    original = Image.open(image_path).convert("RGB")
    cleaned = _strip_annotation_text(original)
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        cleaned.save(tmp.name)
        tmp_path = tmp.name
    try:
        smiles, tokens_with_confidence = predict_SMILES(tmp_path, confidence=True)
    finally:
        Path(tmp_path).unlink(missing_ok=True)
    confidences = [c for _, c in tokens_with_confidence]
    mean_confidence = float(sum(confidences) / len(confidences)) if confidences else 0.0

    # The Ts check runs on the original, unstripped image -- "Ts" is a real
    # structural label JUNK_ANNOTATION_TOKEN_RE never touches, but there's
    # no reason to make it depend on the stripping step succeeding.
    detected_missing_abbreviations = _detected_missing_abbreviations(image_path)
    has_generic_substituent = _has_generic_substituent(smiles)
    mol = Chem.MolFromSmiles(smiles)
    rdkit_valid = mol is not None
    too_many_fragments = _has_too_many_fragments(smiles, mol)

    return {
        "smiles": smiles,
        "mean_confidence": mean_confidence,
        "need_human_review": mean_confidence < MEAN_CONFIDENCE_THRESHOLD
        or bool(detected_missing_abbreviations)
        or has_generic_substituent
        or not rdkit_valid
        or too_many_fragments,
        "detected_missing_abbreviations": detected_missing_abbreviations,
        "has_generic_substituent": has_generic_substituent,
        "too_many_fragments": too_many_fragments,
        "rdkit_valid": rdkit_valid,
    }
