"""Runs DECIMER structure recognition on has_structures=1 figures, flagging
low-confidence results for human review instead of trying to predict
upstream (via CLIP vision or captions) whether a given image is a good
DECIMER target.

That upstream approach was tried first for is_3d specifically and abandoned:
CLIP vision is confounded by ordinary drawing conventions (metal complexes
are routinely drawn with rounded, ball-like atoms even in plain 2D
depictions -- visually similar to a genuine 3D render without being one),
and captions don't always exist for a given figure. DECIMER's own per-token
confidence is a more directly-grounded signal, since it's asking the actual
question that matters: did DECIMER succeed on THIS image, not what visual
category the image belongs to.

Confirmed directly before picking a threshold: a set of clean 2D structures
scored 0.92-0.998 mean confidence, while a 3D ball-and-stick metal-complex
render DECIMER completely misread (fabricated a structure with none of the
real functional groups: no N, no Cl, no metal) scored 0.787. A correctly-
recognized but unusually-colored 2D structure also dipped to 0.790 despite
being right -- confidence isn't perfectly correlated with correctness, but
that's an acceptable asymmetry: flagging a correct structure for human
review is a much cheaper mistake than silently accepting a wrong one.

Confidence alone still misses confirmed, deterministic failure modes:
DECIMER's synthetic training data (generated by RanDepict, which maps
superatom-abbreviation labels to expanded SMILES fragments) has no entry
anywhere for the plain "Ts" (tosyl) abbreviation -- checked directly
against RanDepict's own abbreviation tables and RDKit's built-in default
list. It only defines the far less common "p-Tosyl"/"4-Tosyl"/"Tos"
spellings. Since "Ts" is by far the standard abbreviation in real
synthetic-chemistry literature, the model has essentially never seen it
and reliably misreads it as the element thallium ([Tl]) instead -- visible
even on the public DECIMER web app, not just this pipeline. Thallium is
implausible in routine cross-coupling/catalysis SI documents, and this
substitution happens with moderate-to-high confidence (not a low-
confidence guess), so the existing threshold doesn't catch it. Detecting
the literal label text in the source image via OCR and forcing a review
flag catches this deterministically, independent of what DECIMER's
confidence score says. `--psm 6` (assume one uniform text block) is
required for tesseract to find it -- the default page-segmentation mode
is tuned for structured multi-column pages and fails completely on a
single tight structure crop with sparse embedded text, even though the
label is clearly legible.

Upscaling the crop before OCR turned out to matter more than expected --
not just for accuracy on a given machine, but for reproducibility across
machines. Found by running this exact check on a cloud GPU box for a
larger batch: an identical crop that read "ts" at 96% confidence locally
read as garbage ("+,") on a rented box, even after matching the tesseract
major version and confirming byte-identical eng.traineddata files.
Different tesseract builds (there, conda-forge's; here, Ubuntu apt's)
have different implicit resolution sensitivity for small glyphs, and
without upscaling, a check that passes calibration on one machine can
silently fail on another. 4x upscaling fixed the rented box's read
without changing the local result -- cheap enough to always apply rather
than depend on it happening to not matter this time.

KNOWN_MISSING_ABBREVIATIONS is a small, explicitly-verified list (currently
just "Ts") of labels confirmed absent from DECIMER's training vocabulary --
not a guess. See docs/decimer_abbreviation_gaps.md for how to verify and
add more.
"""

from DECIMER import predict_SMILES
from PIL import Image
import pytesseract

MEAN_CONFIDENCE_THRESHOLD = 0.85
OCR_MIN_CONFIDENCE = 50
OCR_UPSCALE = 4
KNOWN_MISSING_ABBREVIATIONS = {"ts"}


def _detected_missing_abbreviations(image_path):
    img = Image.open(image_path)
    img = img.resize((img.width * OCR_UPSCALE, img.height * OCR_UPSCALE), Image.LANCZOS)
    data = pytesseract.image_to_data(img, config="--psm 6", output_type=pytesseract.Output.DICT)
    return sorted(
        {
            w.strip().lower()
            for w, c in zip(data["text"], data["conf"])
            if w.strip().lower() in KNOWN_MISSING_ABBREVIATIONS and c >= OCR_MIN_CONFIDENCE
        }
    )


def extract_structure(image_path):
    """Returns {"smiles": str, "mean_confidence": float,
    "need_human_review": bool, "detected_missing_abbreviations": [str]}."""
    smiles, tokens_with_confidence = predict_SMILES(image_path, confidence=True)
    confidences = [c for _, c in tokens_with_confidence]
    mean_confidence = float(sum(confidences) / len(confidences)) if confidences else 0.0

    detected_missing_abbreviations = _detected_missing_abbreviations(image_path)

    return {
        "smiles": smiles,
        "mean_confidence": mean_confidence,
        "need_human_review": mean_confidence < MEAN_CONFIDENCE_THRESHOLD
        or bool(detected_missing_abbreviations),
        "detected_missing_abbreviations": detected_missing_abbreviations,
    }
